# Generated by Django 3.1.2 on 2021-03-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210322_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='completed',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de finalizacion'),
        ),
    ]
