# Generated by Django 3.1.2 on 2021-03-27 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_budget_cost_hito_interested_phase_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='interesteds',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio.interested', verbose_name='Interesados'),
            preserve_default=False,
        ),
    ]
