# Generated by Django 3.1.2 on 2021-03-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_project_interesteds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interested',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombre'),
        ),
    ]
