# Generated by Django 3.1.2 on 2021-03-27 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20210327_1603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interested',
        ),
    ]
