# Generated by Django 3.1.2 on 2021-03-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_delete_interested'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'interesado',
                'verbose_name_plural': 'interesados',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='interesteds',
            field=models.ManyToManyField(to='portfolio.Interested', verbose_name='Interesados'),
        ),
    ]
