# Generated by Django 3.1.2 on 2021-03-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_auto_20210328_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='completed',
            field=models.DateField(verbose_name='Fecha de finalizacion'),
        ),
    ]
