# Generated by Django 3.1.2 on 2021-03-28 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_auto_20210328_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='completed',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de finalizacion'),
        ),
    ]
