# Generated by Django 3.1.2 on 2021-04-01 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_project_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.phase', verbose_name='Fase'),
        ),
    ]
