# Generated by Django 3.1.2 on 2021-04-11 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_auto_20210331_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='project',
            name='hito',
        ),
        migrations.RemoveField(
            model_name='project',
            name='interesteds',
        ),
        migrations.RemoveField(
            model_name='project',
            name='presupuesto',
        ),
        migrations.RemoveField(
            model_name='project',
            name='risk',
        ),
        migrations.AddField(
            model_name='budget',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.project', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='cost',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.project', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='hito',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.project', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='interested',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.project', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='risk',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.project', verbose_name='Proyecto'),
        ),
    ]
