# Generated by Django 3.1.2 on 2021-05-09 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_auto_20210410_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cost',
            old_name='amount',
            new_name='amountCost',
        ),
        migrations.RenameField(
            model_name='cost',
            old_name='description',
            new_name='descriptionCost',
        ),
    ]
