# Generated by Django 3.1.2 on 2021-05-09 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_auto_20210509_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='amount',
            new_name='amountBudget',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='description',
            new_name='descriptionBudget',
        ),
        migrations.RenameField(
            model_name='hito',
            old_name='description',
            new_name='descriptionHito',
        ),
        migrations.RenameField(
            model_name='risk',
            old_name='description',
            new_name='descriptionRisk',
        ),
    ]
