# Generated by Django 3.1.2 on 2021-05-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_auto_20210510_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='alcance',
            field=models.TextField(blank=True, null=True, verbose_name='Alcance'),
        ),
        migrations.AddField(
            model_name='project',
            name='objetivos',
            field=models.TextField(blank=True, null=True, verbose_name='Objetivos'),
        ),
    ]
