# Generated by Django 3.1.2 on 2021-08-29 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_auto_20210518_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionSchedule', models.CharField(max_length=200, verbose_name='Descripción actividad')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Comienzo')),
                ('completed', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fin')),
                ('duration', models.IntegerField(verbose_name='Duración')),
            ],
        ),
    ]
