# Generated by Django 3.1.2 on 2021-08-29 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_auto_20210829_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'cronograma', 'verbose_name_plural': 'cronogramas'},
        ),
    ]
