# Generated by Django 3.1.2 on 2021-08-29 22:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0030_auto_20210829_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='completed',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Comienzo'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='descriptionSchedule',
            field=models.CharField(max_length=200, null=True, verbose_name='Descripción actividad'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='duration',
            field=models.IntegerField(null=True, verbose_name='Duración'),
        ),
    ]
