# Generated by Django 3.1.2 on 2021-08-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0031_auto_20210829_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('upload', models.FileField(null=True, upload_to='media')),
                ('url', models.URLField(null=True)),
            ],
        ),
    ]
