# Generated by Django 3.1.2 on 2021-08-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0032_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='files',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
