# Generated by Django 3.1.2 on 2021-08-31 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0033_auto_20210831_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.project', verbose_name='Proyecto'),
        ),
    ]
