# Generated by Django 3.1.2 on 2021-09-05 03:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0034_files_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='order',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='amountCost',
            field=models.IntegerField(verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='descriptionCost',
            field=models.CharField(max_length=200, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='completed',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='descriptionSchedule',
            field=models.CharField(max_length=200, null=True, verbose_name=''),
        ),
    ]
