# Generated by Django 3.1.2 on 2021-09-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0036_auto_20210905_1257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.AddField(
            model_name='project',
            name='estado',
            field=models.CharField(blank=True, choices=[('Iniciado', 'Iniciado'), ('En Progreso', 'En Progreso'), ('Terminado', 'Terminado'), ('Inactivo', 'Inactivo')], max_length=32, null=True),
        ),
    ]
