# Generated by Django 3.1.2 on 2021-09-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0038_auto_20210905_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='impacto',
            field=models.CharField(blank=True, choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='probabilidad',
            field=models.CharField(blank=True, choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='descriptionRisk',
            field=models.CharField(max_length=400, verbose_name=''),
        ),
    ]
