# Generated by Django 3.1.2 on 2021-09-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0040_auto_20210905_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interested',
            name='name',
            field=models.CharField(max_length=200, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='estado',
            field=models.CharField(blank=True, choices=[('Sin empezar', 'Sin empezar'), ('En Progreso', 'En Progreso'), ('Terminada', 'Terminada')], max_length=32, null=True),
        ),
    ]
