# Generated by Django 3.1.2 on 2021-09-11 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0041_auto_20210910_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='alcance',
            field=models.TextField(null=True, verbose_name='Alcance'),
        ),
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Encargado'),
        ),
        migrations.AlterField(
            model_name='project',
            name='estado',
            field=models.CharField(choices=[('Iniciado', 'Iniciado'), ('En Progreso', 'En Progreso'), ('Terminado', 'Terminado'), ('Inactivo', 'Inactivo')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='objetivos',
            field=models.TextField(null=True, verbose_name='Objetivos'),
        ),
        migrations.AlterField(
            model_name='project',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.phase', verbose_name='Fase'),
        ),
    ]
