# Generated by Django 3.1.2 on 2021-09-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0042_auto_20210911_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interested',
            name='influencia',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Alta', 'Alta')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='interested',
            name='interes',
            field=models.CharField(choices=[('Bajo', 'Bajo'), ('Alto', 'Alto')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='impacto',
            field=models.CharField(choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='probabilidad',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='estado',
            field=models.CharField(choices=[('Sin empezar', 'Sin empezar'), ('En Progreso', 'En Progreso'), ('Terminada', 'Terminada')], max_length=32, null=True),
        ),
    ]
