# Generated by Django 3.1.2 on 2021-09-18 16:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0043_auto_20210911_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='objetivos',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Objetivos'),
        ),
    ]
