# Generated by Django 3.1.2 on 2021-10-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0044_auto_20210918_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='objetivos',
            field=models.TextField(null=True, verbose_name='Objetivos'),
        ),
    ]
