# Generated by Django 3.1.2 on 2021-05-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_profile_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profesion',
            field=models.TextField(blank=True, null=True, verbose_name='Profesión u Oficio'),
        ),
    ]
