# Generated by Django 3.1.2 on 2021-05-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_profile_profesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profesion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Profesión u Oficio'),
        ),
    ]
